@startuml
' with below line the SVG is not scaled/zoomed to fit the outer frame
skinparam svgDimensionStyle true
'skinparam linetype ortho
skinparam linetype polyline
'skinparam ranksep 100
'scale max 200 width 
agent "[[#radiation-oncology-information-system Radiation Oncology Information System (ROIS)]]" as ROIS
agent "[[#treatment-management-system Treatment Management System (TMS)]]" as TMS
agent "[[#ro-resource-repo RO Resource Repo]]" as REPO
TMS -down-> REPO : [[RO-SMRT-xx.html Subscribe ~[RO-SMRT-xx~]]] \n [[RO-SMRT-01.html Query Treatment Strategy ~[RO-SMRT-01~]]] \n [[RO-SMRT-02.html Query Diagnosis ~[RO-SMRT-02~]]]
ROIS -down-> REPO : [[RO-SMRT-xx.html Subscribe ~[RO-SMRT-xx~]]] \n [[RO-SMRT-xx.html Report Approval ~[RO-SMRT-xx~]]]
@enduml
