@startuml
' with below line the SVG is not scaled/zoomed to fit the outer frame
skinparam svgDimensionStyle true
'skinparam linetype ortho
skinparam linetype polyline
'skinparam ranksep 100
'scale max 200 width

agent "[[#radiation-oncology-information-system Radiation Oncology Information System (ROIS)]]" as ROIS
agent "[[#treatment-management-system Treatment Management System (TMS)]]" as TMS
agent "Hospital Information\nSystem (HIS)" as HIS #line.dashed
agent "Object Store\n(DICOM)" as OST #line.dashed

HIS .down.> ROIS : (external) patient registration
ROIS -down-> TMS : Sync Patient Demographics [RO-SMRT-01] \n Sync Treatment Appointment [RO-SMRT-02] \n Report Treatment Approval [RO-SMRT-05] \n Report Patient Check-in [RO-SMRT-06]
TMS -up-> ROIS : Retrieve Prescription Summary [RO-SMRT-03] \n Report Planning Artifacts [RO-SMRT-04] \n Report Patient Check-in [RO-SMRT-06] \n Report Treatment Artifacts [RO-SMRT-07] \n Image Approval [RO-SMRT-08] \n Report Treatment USCDI Data [RO-SMRT-09]
ROIS .down.> OST : (external) DICOM retrieve\nC-MOVE / C-GET / QIDO-RS / WADO-RS
@enduml
