@startuml
skinparam svgDimensionStyle true
hide footbox
participant "Requester" as Requester
participant "Responder" as Responder
activate Requester
activate Responder
Requester -> Responder : 1. Query Treatment Strategy ServiceRequests
Responder --> Requester : 2. Return Treatment Strategy ServiceRequests Bundle
deactivate Requester
deactivate Responder
@enduml
