@startuml
skinparam svgDimensionStyle true
hide footbox
participant "TMS" as TMS
participant "ROIS" as ROIS
activate TMS
activate ROIS
TMS -> ROIS : 1. Retrieve Prescription Summary request
ROIS --> TMS : 2. Prescription Summary
deactivate TMS
deactivate ROIS
@enduml
