@startuml
skinparam svgDimensionStyle true
hide footbox
participant "ROIS" as ROIS
participant "TMS" as TMS
activate ROIS
activate TMS
ROIS -> TMS : 1. Sync Patient Demographics\n(demographics, encounter, photo)
ROIS -> TMS : 2. Demographic / appointment / identifier update
deactivate ROIS
deactivate TMS
@enduml
