@startuml
skinparam svgDimensionStyle true
hide footbox
participant "ROIS" as ROIS
participant "TMS" as TMS
activate ROIS
activate TMS
ROIS -> TMS : 1. Sync Treatment Appointment\n(scheduled treatment fractions)
ROIS -> TMS : 2. Appointment update / cancellation
deactivate ROIS
deactivate TMS
@enduml
