@startuml
skinparam svgDimensionStyle true
hide footbox
participant "TMS" as TMS
participant "ROIS" as ROIS
activate TMS
activate ROIS
TMS -> ROIS : 1. Report Planning Artifacts\n(FHIR message, refs DICOM RT objects)
ROIS -> ROIS : 2. Retrieve required artifacts (DICOM)
deactivate TMS
deactivate ROIS
@enduml
