@startuml
skinparam svgDimensionStyle true
hide footbox
participant "TMS" as TMS
participant "ROIS" as ROIS
participant "OST" as OST
activate TMS
activate ROIS
TMS -> ROIS : 1. Report Planning Artifacts\n(FHIR message, refs DICOM RT objects)
ROIS -> OST : 2. Retrieve planning artefacts (DICOM)
deactivate TMS
deactivate ROIS
@enduml
