@startuml
skinparam svgDimensionStyle true
hide footbox
participant "ROIS" as ROIS
participant "TMS" as TMS
activate ROIS
activate TMS
ROIS -> TMS : 1. Report Treatment Approval\n(FHIR message)
TMS -> TMS : 2. Add approval to plan
deactivate ROIS
deactivate TMS
@enduml
