@startuml
skinparam svgDimensionStyle true
hide footbox
participant "ROIS" as ROIS
participant "TMS" as TMS
activate ROIS
activate TMS
ROIS -> TMS : 1a. Report Patient Check-in (checked-in at ROIS)
TMS -> ROIS : 1b. Report Patient Check-in (checked-in at TMS)
deactivate ROIS
deactivate TMS
@enduml
